"""
bank_to_sfz.py - Convert mXXX-velX-fXX.wav instrument bank to SFZ format

Usage:
    python bank_to_sfz.py <instrument_dir> [options]

Examples:
    python bank_to_sfz.py C:/samples/rhodes
    python bank_to_sfz.py C:/samples/rhodes --sr 48 --out rhodes.sfz
    python bank_to_sfz.py C:/samples/rhodes --relative-paths

Output:
    <instrument_dir>.sfz  (or --out path)

SFZ key ranges:
    Each sampled note is stretched to cover the chromatic range halfway
    to its neighbours (standard keymap interpolation). The lowest note
    covers from MIDI 0 and the highest to MIDI 127.

SFZ velocity ranges:
    Velocity layers 0-(N-1) are mapped to equal-width bands across 0-127.
    Example for 8 layers: 0->0-15, 1->16-31, ..., 7->112-127
"""

import os
import re
import sys
import json
import argparse
from collections import defaultdict


NOTE_NAMES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']


def midi_to_note_name(midi: int) -> str:
    """60 -> 'C4',  69 -> 'A4'"""
    octave = midi // 12 - 1
    name   = NOTE_NAMES[midi % 12]
    return f'{name}{octave}'


def midi_to_hz(midi: int) -> float:
    return 440.0 * 2 ** ((midi - 69) / 12.0)


def vel_layer_range(vel_idx: int, n_layers: int) -> tuple[int, int]:
    """Map vel layer index to MIDI velocity range 0-127."""
    lo = round(vel_idx * 127 / n_layers)
    hi = round((vel_idx + 1) * 127 / n_layers) - 1
    if vel_idx == n_layers - 1:
        hi = 127
    return lo, hi


def key_ranges(midi_notes: list[int]) -> dict[int, tuple[int, int]]:
    """
    For each sampled note compute (lokey, hikey) that covers the range
    halfway to its neighbours. First note covers from 0, last to 127.
    """
    notes  = sorted(midi_notes)
    ranges = {}
    for i, note in enumerate(notes):
        if i == 0:
            lo = 0
        else:
            lo = (notes[i - 1] + note + 1) // 2
        if i == len(notes) - 1:
            hi = 127
        else:
            hi = (note + notes[i + 1]) // 2
        ranges[note] = (lo, hi)
    return ranges


def scan_bank(bank_dir: str, sr_filter: int = None) -> dict:
    """
    Scan bank_dir for mXXX-velX-fXX.wav files.
    Returns {midi: {vel: filepath}}
    """
    pattern = re.compile(r'^m(\d{3})-vel(\d+)-f(\d+)\.wav$', re.IGNORECASE)
    bank    = defaultdict(dict)

    for fname in os.listdir(bank_dir):
        m = pattern.match(fname)
        if not m:
            continue
        midi = int(m.group(1))
        vel  = int(m.group(2))
        sr   = int(m.group(3))
        if sr_filter and sr != sr_filter:
            continue
        path = os.path.join(bank_dir, fname)
        # Prefer higher sr if both exist and no filter
        existing = bank[midi].get(vel)
        if existing is None:
            bank[midi][vel] = (path, sr)
        else:
            _, existing_sr = existing
            if sr > existing_sr:
                bank[midi][vel] = (path, sr)

    return bank


def build_sfz(bank_dir: str,
              out_path: str,
              sr_filter: int = None,
              relative_paths: bool = True,
              instrument_name: str = None):

    bank = scan_bank(bank_dir, sr_filter)
    if not bank:
        print(f'Zadne soubory mXXX-velX-fXX.wav nenalezeny v: {bank_dir}')
        sys.exit(1)

    all_midi  = sorted(bank.keys())
    all_vels  = sorted({v for layers in bank.values() for v in layers})
    n_layers  = max(all_vels) + 1
    k_ranges  = key_ranges(all_midi)

    # Detect actual sample rates present
    all_srs = sorted({sr for layers in bank.values() for _, sr in layers.values()})

    idef_path = os.path.join(bank_dir, 'instrument-definition.json')
    if instrument_name is None and os.path.exists(idef_path):
        try:
            with open(idef_path, encoding='utf-8') as f:
                idef = json.load(f)
            instrument_name = idef.get('instrumentName', os.path.basename(bank_dir))
        except Exception:
            instrument_name = os.path.basename(bank_dir)
    if instrument_name is None:
        instrument_name = os.path.basename(bank_dir)

    sfz_dir = os.path.dirname(os.path.abspath(out_path))

    lines = []
    lines.append(f'// {instrument_name}')
    lines.append(f'// Generated by bank_to_sfz.py')
    lines.append(f'// Notes: {midi_to_note_name(all_midi[0])} ({all_midi[0]}) - '
                 f'{midi_to_note_name(all_midi[-1])} ({all_midi[-1]})')
    lines.append(f'// Velocity layers: {n_layers}')
    lines.append(f'// Sample rates: {", ".join(str(s)+"kHz" for s in all_srs)}')
    lines.append('')
    lines.append('<control>')
    lines.append(f'default_path=')
    lines.append('')

    for vel_idx in all_vels:
        lovel, hivel = vel_layer_range(vel_idx, n_layers)

        lines.append(f'// --- Velocity layer {vel_idx} ({lovel}-{hivel}) ---')
        lines.append('<group>')
        lines.append(f'  lovel={lovel}')
        lines.append(f'  hivel={hivel}')
        lines.append('')

        for midi in all_midi:
            entry = bank[midi].get(vel_idx)
            if entry is None:
                # Fallback: use nearest velocity layer for this note
                available = bank[midi]
                if not available:
                    continue
                nearest = min(available.keys(), key=lambda v: abs(v - vel_idx))
                entry = available[nearest]

            fpath, sr = entry

            if relative_paths:
                try:
                    sample_ref = os.path.relpath(fpath, sfz_dir).replace('\\', '/')
                except ValueError:
                    # Different drive on Windows
                    sample_ref = os.path.abspath(fpath).replace('\\', '/')
            else:
                sample_ref = os.path.abspath(fpath).replace('\\', '/')

            lokey, hikey = k_ranges[midi]
            hz = midi_to_hz(midi)
            note_name = midi_to_note_name(midi)

            lines.append(f'  <region>')
            lines.append(f'    sample={sample_ref}')
            lines.append(f'    pitch_keycenter={midi}  // {note_name} {hz:.1f} Hz')
            lines.append(f'    lokey={lokey}')
            lines.append(f'    hikey={hikey}')
            lines.append('')

        lines.append('')

    sfz_text = '\n'.join(lines)

    os.makedirs(sfz_dir, exist_ok=True)
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(sfz_text)

    print(f'[bank_to_sfz] Nastroj:  {instrument_name}')
    print(f'[bank_to_sfz] Noty:     {len(all_midi)}  ({midi_to_note_name(all_midi[0])} - {midi_to_note_name(all_midi[-1])})')
    print(f'[bank_to_sfz] Vrstvy:   {n_layers}  velocity rozsahy:')
    for v in all_vels:
        lo, hi = vel_layer_range(v, n_layers)
        print(f'              vel{v} -> MIDI vel {lo:3d}-{hi:3d}')
    print(f'[bank_to_sfz] Vystup:   {out_path}')


def main():
    ap = argparse.ArgumentParser(
        description='Convert mXXX-velX-fXX.wav instrument bank to SFZ format',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    ap.add_argument('bank_dir', metavar='BANK_DIR',
                    help='Directory containing mXXX-velX-fXX.wav files')
    ap.add_argument('--out', metavar='FILE',
                    help='Output .sfz path (default: <bank_dir>.sfz)')
    ap.add_argument('--sr', type=int, default=None, metavar='KHZ',
                    help='Use only this sample rate (e.g. 48 for f48 files). '
                         'Default: prefer higher SR if both exist.')
    ap.add_argument('--name', metavar='NAME',
                    help='Instrument name (default: from instrument-definition.json or dir name)')
    ap.add_argument('--absolute-paths', action='store_true',
                    help='Use absolute paths in SFZ (default: relative)')
    args = ap.parse_args()

    bank_dir = os.path.abspath(args.bank_dir)
    if args.out:
        out_path = args.out
    else:
        out_path = bank_dir.rstrip('/\\') + '.sfz'

    build_sfz(
        bank_dir         = bank_dir,
        out_path         = out_path,
        sr_filter        = args.sr,
        relative_paths   = not args.absolute_paths,
        instrument_name  = args.name,
    )


if __name__ == '__main__':
    main()
